### ISSUE TITLE
Workshop content

### ISSUE THREAD

**Issue by mblue9** [stemangiola/rpharma2020_tidytranscriptomics#1]
Draft (tick when 1st draft is added to this repo)

**Core** (updated version of Bioc2020 e.g. using identify_abundant)

- [x] Data exploration
- [x] Data dimensionality reduction and clustering
- [x] Differential gene expression analysis
- [x] Data visualisation

**Extended**

- [x] Comparison of different differential transcript abundance testing tools (also gives more in-depth info on what test_differential_abundance is doing)
- [x] Strip-chart comparing all normalisations of top genes (also gives more in-depth info on what scale_abundance is doing)
- [x] An example of nested analysis (e.g. run independent analysis for two separate batched as easily as doing it all together)

**Single-cell**

- [x] Highlights of tidyseurat

**Comment by mblue9** [comment]
@stemangiola I started a draft for what we could cover what do you think?

**Comment by mblue9** [comment]
For the RTT testing should I ask Phil for the current (or other?) master versions of tidybulk, tidySCE and tidyseurat (aswell as the workshop)?
e.g.
`install_github(c("stemangiola/rpharma2020_tidytranscriptomics", "stemangiola/tidybulk", "stemangiola/tidySCE", "stemangiola/tidyseurat"))`

**Comment by stemangiola** [comment]
> 
> 
> For the RTT testing should I ask Phil for the current (or other?) master versions of tidybulk, tidySCE and tidyseurat (aswell as the workshop)?
> e.g.
> `install_github(c("stemangiola/rpharma2020_tidytranscriptomics", "stemangiola/tidybulk", "stemangiola/tidySCE", "stemangiola/tidyseurat"))`

We might not need both tidyseurat and tisySCE. Let's pick one. I used a bit more tidyseurat for my analyses, but if you think tidySCE would fit better happy to go with it. The problem of including them both being that they have identical function name. In real word I don't imagine people using them together.

**Comment by mblue9** [comment]
>We might not need both tidyseurat and tisySCE. Let's pick one. I used a bit more tidyseurat for my analyses, but if you think tidySCE would fit better happy to go with it. The problem of including them both being that they have identical function name. In real word I don't imagine people using them together.

Ah yes I was going to ask you if we need both. Ok will we plan to use tidyseurat then? As seurat is also the main single cell tool used at Pmac. And tidySCE is not in an official repo (yet 😄)  But I might ask Phil to install both so we have them in case it turns out they want us to demo Bioc packages.

**Comment by mblue9** [comment]
I made a really rough draft of the estimated content and timings to the [README ](https://github.com/stemangiola/rpharma2020_tidytranscriptomics/blob/master/README.md)
Feel free to alter. We most likely will need to trim down as probably hard to cover all that content well in 2 hours. But better to write a bit more than we need and then cut down I think.

**Comment by stemangiola** [comment]
FYI https://stemangiola.github.io/tidybulk/articles/comparison_with_base_R.html

**Comment by stemangiola** [comment]
I will do the case study for comparison of DE methods.

**Comment by mblue9** [comment]
>I will do the case study for comparison of DE methods.

Ok I put a tiny bit on that in the vignette so you could remove that when you're ready 
https://github.com/stemangiola/rpharma2020_tidytranscriptomics/blob/master/vignettes/tidytranscriptomics.Rmd#L536-L551

I could start adding in something for one of these:
-Strip-chart comparing all normalisations of top genes - I think you sent me a plot of that before? do you have the code for it?
-An example of nested analysis - do you have an example in mind of an independent analysis we could do with the airway dataset? 
-Highlights of tidyseurat - should we use the same dataset as in the tidyseurat vignette and some of the code from there?

**Comment by stemangiola** [comment]
> Strip-chart comparing all normalisations of top genes - I think you sent me a plot of that before? do you have the code for it?

I think is one of the examples in the article. Let's try to update tidytranscriptomics repository with new code, and then take that code for the specific workshops, so we have always a central source.



> An example of nested analysis - do you have an example in mind of an independent analysis we could do with the airway dataset?

I have a case study in the tidytranscriptomics repo. In general nested analyses could be done
- on single-cell sudo bulk, nesting for cell type for example
- on bulk data nesting for batches and comparing DE gene overlap at higher level
- ...



> Highlights of tidyseurat - should we use the same dataset as in the tidyseurat vignette and some of the code from there?

Sure

**Comment by mblue9** [comment]
>I think is one of the examples in the article. 

Ok great I'll have a look.

>Let's try to update tidytranscriptomics repository with new code, and then take that code for the specific workshops, so we have always a central source.

Yes but can we add the code from here to tidytranscriptomics repo after this workshop? as this workshop is only ~2 weeks away so better (for me anyway) to focus on one repo rather than updating 2 in case I forget to update one.

>I have a case study in the tidytranscriptomics repo. In general nested analyses could be done:
on single-cell sudo bulk, nesting for cell type for example
on bulk data nesting for batches and comparing DE gene overlap at higher level

Is another option that it could be used to compare the overlap in DE genes from the DE comparison you're doing? could you nest by method and count or visualise the no. of overlapping DE genes?

**Comment by stemangiola** [comment]
> as this workshop is only ~2 weeks away so better (for me anyway) to focus on one repo rather than updating 2 in case I forget to update one.

Cool



> could you nest by method and count or visualise the no. of overlapping DE genes?

Yes, however this is just a tibble nest, does not really use tidybulk operations inside the nest. You think the batch example is not good/feasible?

We can also just think about another simple example where we nest data and we do one of
- scaling
- DE
- PCA
- ...

**Comment by mblue9** [comment]
Ok cool yes a simple example like that could be good I think. As was thinking the airway dataset may not be a great dataset to show nesting by batch and DE as if we were to nest by batch (cell line) then there's only 1 treated vs 1 untreated sample.

**Comment by stemangiola** [comment]
> then there's only 1 treated vs 1 untreated sample.

 I though of that, however it could be just a dummy example. Can any DE method do 1 vs 1? I would think so.

**Comment by mblue9** [comment]
>Can any DE method do 1 vs 1? I would think so.

edgeR can but you have to change the method a bit https://support.bioconductor.org/p/124721/ 
DESeq cannot https://bioconductor.org/packages/release/bioc/vignettes/DESeq2/inst/doc/DESeq2.html#can-i-use-deseq2-to-analyze-a-dataset-without-replicates
limma-voom also cannot I think https://support.bioconductor.org/p/69775/

I think that might end up overly complicating things if the idea is to just show nesting, so maybe lets think a bit more about what could be good to nest for the ariway dataset or else use the single cell example.

**Comment by stemangiola** [comment]
Hello @mblue9 , the case study (draft) for DE method comparison is complete https://github.com/stemangiola/tidytranscriptomics/issues/8

Basically all packages will need to be installed from github as I did some improvements/fixes


I will try to complete the comparison of normalization methods too as case study

**Comment by mblue9** [comment]
Great! 
So by all packages need to be installed from github do you mean these ones? So we setup the project like this
```
BiocManager::install("stemangiola/tidybulk", version="devel")
BiocManager::install("stemangiola/tidyseurat", version="devel")
BiocManager::install("stemangiola/rpharma2020_tidytranscriptomics", version="devel")
```

**Comment by stemangiola** [comment]
- tidybulk
- tidyseurat (pretty sure)
- tidygate

should be installed from github

**Comment by stemangiola** [comment]
@mblue9 I have edited the first comment so now they are check-boxes. We can tick the boxes for which content is integrated into the main workshop file.

We really have short time to do these things, I am panicking a bit :) On Monday we can meet to discuss the plan to complete the workshop material and practice at least once.

**Comment by mblue9** [comment]
No need to panic we will get it done. Yes let's meet Monday to discuss the plan.

**Comment by mblue9** [comment]
I've tested your case studies for the DE comparison and nested analysis (nice work on them!) plus the tidyseurat vignette in the RStudio Cloud project and all work there. 

And I've pushed the files from RStudio Cloud into this repo. I made just a few small edits so far. If you make any changes to the case studies could you make them in this repo now instead of tidytranscriptomics repo?

For above checklist I've ticked which parts have been added to the repo as a 1st draft. So just the normalisation left to do.

I don't think we need it all in one Rmd I think we can have separate Rmds for the different parts We could maybe number them 1,2,3 like the schedule. We can discuss what makes sense on Monday. 

Then we need to go over it all to make sure it makes sense and is clear.

And add a few exercises for the new parts.

**Comment by stemangiola** [comment]
I like you add references, good job! tidybulk 1.1.8 is on its way into Bioconuctor, I'm pretty sure we could use tidyseurat present in CRAN, what else.. tidygate is on its way into CRAN too. TidyHeatmap is also good from CRAN I believe. So before the conference, for what it matters we may be able to use only official repos.

**Comment by mblue9** [comment]
That could be good to have them in official repos. It's not absolutely essential I think but it could be nice for the workshop attendees to be able to install on their own computers in the usual ways if they want to do that.

**Comment by mblue9** [comment]
When tidybulk 1.1.8 is in bioc devel let me know as that might fix the error here. 
It's weird.. even though it's installing tidybulk 1.1.8 from Github 
```
2020-09-26T13:58:49.0662392Z BiocManager::install("stemangiola/tidybulk", version="devel")
2020-09-26T13:58:51.5435110Z Installing github package(s) 'stemangiola/tidybulk'
2020-09-26T13:58:51.7124643Z Downloading GitHub repo stemangiola/tidybulk@HEAD
2020-09-26T14:02:14.6003684Z ─  preparing ‘tidybulk’:
2020-09-26T14:02:43.9997797Z ─  building ‘tidybulk_1.1.8.tar.gz’
2020-09-26T14:02:44.8688170Z * installing *source* package ‘tidybulk’ ...
2020-09-26T14:03:14.3654810Z * DONE (tidybulk)
```

it's failing with 
```
Quitting from lines 89-120 (comparison_differential_transcription.Rmd) 
Error: processing vignette 'comparison_differential_transcription.Rmd' failed with diagnostics:
unused argument (prefix = "edgerQLT_")
--- failed re-building ‘comparison_differential_transcription.Rmd’
```

**Comment by mblue9** [comment]
I made a few slides to use at the beginning to introduce RNA-seq 
https://docs.google.com/presentation/d/1oAx9KZJYUvq2MF4H9hvh11sKH3fxmWrusW80VxP1PhA/edit#slide=id.p

**Comment by stemangiola** [comment]
> 
> 
> I like you add references, good job! tidybulk 1.1.8 is on its way into Bioconuctor, I'm pretty sure we could use tidyseurat present in CRAN, what else.. tidygate is on its way into CRAN too. TidyHeatmap is also good from CRAN I believe. So before the conference, for what it matters we may be able to use only official repos.

I think now we can use official repositories for all packages

**Comment by stemangiola** [comment]
To do list:

- [x] take off plotly of scatter plot DE
- [x] add exercise on DE comparison
- [x] add stripcharts
- [ ] add exercise on single cell

**Comment by mblue9** [comment]
I made a separate issue for to dos as some are not creating content https://github.com/stemangiola/rpharma2020_tidytranscriptomics/issues/5

**Comment by mblue9** [comment]
Question  - in the DE comparison https://stemangiola.github.io/rpharma2020_tidytranscriptomics/articles/tidytranscriptomics.html#comparison-of-differential-analysis-methods
is there a reason to use identify_abundant and then keep_abundant repetitively? Could we just use  keep_abundant or is identify_abundant needed by the methods e.g. deseq2?

**Comment by stemangiola** [comment]
Sure in this case using keep_abundant at the beginning is better to avoid repetitions (normally I prefer identify_abundant to not drop any info as matter of principle).

**Comment by mblue9** [comment]
Well happy to stick to your principles and use identify_abundant 😄 . As also may be good to teach people to use that one as they can easily check the de results for genes of interest & see if they're significant, not significant or not abundant (am starting to wonder if keep_abundant is needed as if people use identify_abundant then could they just use `filter(.abundant)`?)

**Comment by stemangiola** [comment]
My main point was that in this case I agree with you, too many filtering when one is enough. Sometimes is good to be pragmatic and practical.

Feel free to drop them all and replace identify_abundant

**Comment by mblue9** [comment]
Ok done, yes lets just keep it simple for the moment. I got that was your main point it just made me think that it might be worth considering in the future whether 2 filtering functions are needed...but totally up to you.

**Comment by mblue9** [comment]
Am trying to add a bit more explanation to the gate bit, can you give me a bit more info to understand this part

```{r, eval=FALSE}
de_gate <- 
  de_all %>%
  
  gate(
    feature,
    edgerQLT_PValue, 
    deseq2_pvalue, 
    opacity=0.3, 
    how_many_gates = 2 
  )
```

```{r, echo=FALSE}
de_gate <- 
  de_all %>%
  
  gate(
    feature,
    edgerQLT_PValue, 
    deseq2_pvalue, gate_list = rpharma2020tidytranscriptomics::de_gate_gates
  )

de_gate
```

1) The 1st block errors is that because there's not enough points?

2) The 2nd block uses the data in rpharma2020tidytranscriptomics::de_gate_gates
How did you come up with those gates?

3) How does tidygate decide what points to include in gates?

**Comment by stemangiola** [comment]
Basically gate function allows to interactively select some points and label them in the tibble. Since the Rmd file is not compiled interactively I have used an option of tidygate where you can programmatically gate points, save the gates and recall them in your code if you execute it in the future.

If you have a pipeline you want it to be reproducible and not having to draw gates every time you execute it.

**Comment by mblue9** [comment]
As discussed I will try to add a sentence to explain the gate a bit more for people like me :smile:

Question on the nesting part..

Why not facet by marker here:

```
markers_df %>%
    ggplot(aes(cell_type, count_scaled +1 )) + 
    geom_boxplot() + 
    scale_y_log10() + 
    custom_theme
```
as wouldn't you want to know if some markers are more cell-type specific than others?

**Comment by mblue9** [comment]
Ok I added faceting to the markers plot here https://github.com/stemangiola/rpharma2020_tidytranscriptomics/pull/14/commits/e1aca931519171b2b3abb33cdc58adefb821b34f
