### ISSUE TITLE
tab order

### ISSUE THREAD

**Issue by stemangiola** [stemangiola/rpharma2020_tidytranscriptomics#13]
What do you think to put the tab order as:

**Background | Workshop | solutions | Supplementary**

Ideally in the future the supplementary will be included as resource in the tidytranscriptomic repo.

**Comment by mblue9** [comment]
Sound good. We could omit Supplementary from the tabs and just leave it as a link in the Part 1 section? 

As we have no supplementary for Parts 2 & 3 but my reason to include it somwehwere is that it shows a few things that might be useful like how to start from tables if they don't have a SE object.
