### ISSUE TITLE
avoid global import of org.xxx.db

### ISSUE THREAD

**Issue by stemangiola** [stemangiola/rpharma2020_tidytranscriptomics#16]
The 

```
library(org.Hs.eg.db)
library(org.Dm.eg.db)
```

affect al lot of libraries as they include tidyverse function names.

I would suggest to use this libraries as 

```
org.Dm.eg.db:::
```

So to not compomise the rest of the packages

**Comment by mblue9** [comment]
I actually tried that already it was just a bit ugly as seems you have to do 

`counts_tt <- counts_format %>% mutate(symbol = AnnotationDbi::mapIds(org.Hs.eg.d::org.Hs.eg.db, keys = as.character(feature), keytype = "ENSEMBL", column="SYMBOL", multiVals = "first"))`

so I went with loading in the org libraries before the tidyverse ones but if you think it's better to use :: 
lets change to that?

**Comment by stemangiola** [comment]
I think is better, because for example I'm playing with the code interactively and executing code before and after that, and it is failing because `select` is compromised.

In the real word you have to do the ugly thing to operate normally in your analyses.

**Comment by mblue9** [comment]
Ok I'll change it to :: then.

**Comment by mblue9** [comment]
Done in https://github.com/stemangiola/rpharma2020_tidytranscriptomics/pull/21
