### ISSUE TITLE
Error with using rename

### ISSUE THREAD

**Issue by mblue9** [stemangiola/rpharma2020_tidytranscriptomics#17]
My PR just failed due to  rename

```
unable to find an inherited method for function 'rename' for signature '"tidybulk"'
--- failed re-building ‘tidytranscriptomics.Rmd’
```

From this code
```
de_all %>%
rename(deseq2_PValue = deseq2_pvalue, deseq2_FDR = deseq2_padj)
```

Is that a tidybulk bug? as I see tidybulk says it has a rename function so do you know why that doesn't work?

I can fix it by using `dplyr::rename`

**Comment by stemangiola** [comment]
Hello I don't think is a bug. Probably, there is another package (e.g. BioC annotations) other than tidyverse or tidybulk that has rename as function.

This is why is generally better to `library` just the packages that we use a lot, and use :: for the other ones that we use once.

It could be tidyseurat


```
Help on topic 'rename' was found in the following packages:

Modify names by name, not position.

(in package plyr in library /stornext/Home/data/allstaff/m/mangiola.s/R/x86_64-pc-linux-gnu-library_interactive/rstudio)
Rename columns

(in package tidybulk in library /stornext/Home/data/allstaff/m/mangiola.s/R/x86_64-pc-linux-gnu-library_interactive/rstudio)
Rename columns

(in package dplyr in library /stornext/Home/data/allstaff/m/mangiola.s/R/x86_64-pc-linux-gnu-library_interactive/rstudio)
Rename

(in package reshape in library /stornext/Home/data/allstaff/m/mangiola.s/R/x86_64-pc-linux-gnu-library_interactive/rstudio)
Objects exported from other packages

(in package plotly in library /stornext/Home/data/allstaff/m/mangiola.s/R/x86_64-pc-linux-gnu-library_interactive/rstudio)
Rename columns

(in package tidyseurat in library /stornext/Home/data/allstaff/m/mangiola.s/R/x86_64-pc-linux-gnu-library_interactive/rstudio)
Vector objects

(in package S4Vectors in library /stornext/Home/data/allstaff/m/mangiola.s/R/x86_64-pc-linux-gnu-library_interactive/rstudio)
```

**Comment by mblue9** [comment]
It can't be tidyseurat as that doesn't get library loaded until after this point. 

If you want to reproduce you can start a fresh R session and run the tidytranscriptomics.Rmd from the PR. 

But I wonder if it's plotly?  If it is plotly should we  use plotly::  or library load plotly before tidybulk?

**Comment by stemangiola** [comment]
Sure doing now

**Comment by mblue9** [comment]
I just tried commenting out library(plotly) and using plotly:: and still get the error with rename.

**Comment by mblue9** [comment]
Got it, it's the airway library that's causing it

**Comment by stemangiola** [comment]
airway may be loaded after tidybulk, and it is importing plyr, that has now the priority over tidybulk.

(all this happens because S3 object system is very primitive) If R had global methods (maybe S4 has) this would not happen because there is just one method that accepts tidybulk object.

**Comment by mblue9** [comment]
Ah good to know! I had no idea why it was happening as couldn't see a rename function for airway. 

So should we run library(airway) before library(tidybulk)? Or use :: I just tried to see if I could get the data with `airway <- airway::airway` but that doesn't work.

**Comment by mblue9** [comment]
For the moment I've changed to load airway first here https://github.com/stemangiola/rpharma2020_tidytranscriptomics/pull/15/commits/ad0d006cdc0df6ffad02864b418c0912524298af but if we should change that let me know.

**Comment by mblue9** [comment]
I don't understand this do you?

My PR is still failing here https://github.com/stemangiola/rpharma2020_tidytranscriptomics/runs/1192123663?check_suite_focus=true even though I've removed as many `library()` as I can.

It seems there is an S4vectors library being loaded but in the supplementary.Rmd that's masking the tidybulk rename in the tidytranscriptomics.Rmd

```
--- re-building ‘supplementary.Rmd’ using rmarkdown
Loading required package: SummarizedExperiment
Loading required package: GenomicRanges
Loading required package: stats4
Loading required package: BiocGenerics
Loading required package: parallel
...
Loading required package: S4Vectors

Attaching package: 'S4Vectors'

The following object is masked from 'package:tidybulk':

    rename

...
--- finished re-building ‘supplementary.Rmd’

--- re-building ‘tidytranscriptomics.Rmd’ using rmarkdown
...
Quitting from lines 656-659 (tidytranscriptomics.Rmd) 
Error: processing vignette 'tidytranscriptomics.Rmd' failed with diagnostics:
unable to find an inherited method for function 'rename' for signature '"tidybulk"'
--- failed re-building ‘tidytranscriptomics.Rmd’
```

**Comment by mblue9** [comment]
Removing the supplementary and solutions Rmds fixes it https://github.com/stemangiola/rpharma2020_tidytranscriptomics/runs/1192543606?check_suite_focus=true

This is so very weird as I assumed all the vignettes were tested independently and didn't think the library calls would interfere with each other but seems like they do. 

Also thought that even if that is happening, as library tidybulk is called after airway in tidytranscriptomics.Rmd then tidybulk rename should still get priority in that Rmd so no idea why this is happening here 😖

**Comment by stemangiola** [comment]
I'm sorry it's frustrating. Look we can use tidybulk::rename if needed. It's ugly but not th end of the world

**Comment by stemangiola** [comment]
can we have a short chat, just to quickly ask few questions. 
___
I realised it's late sorry XD. Tomorrow we can have a chat and find a solution. Will be easy!

**Comment by mblue9** [comment]
Ok cool. Yep we could use tidybulk::rename or some other workaround if need be.

I am a bit frustrated but it's with the Github actions environment because I don't understand what's happening here as it works fine locally & it also worked fine with your PR that also had the rename in it so maybe it's just bad luck with that specific PR 😄

**Comment by mblue9** [comment]
I decided to add `eval=FALSE` to the rename code as it's not important to see the output as it's just a tip so that got around the error without needing to use tidybulk::rename.
