### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by mblue9** [stemangiola/rpharma2020_tidytranscriptomics#19]
Just noting some things I will ask you tomorrow 

I like the new part by the way

-  What about a title something like Cell type composition analysis instead of Study of cellularity? (maybe just me but I associate cellularity with amount of tumor cells rather than cell types)
- What about doing the Deconvolution of Cell types after the Nested analysis instead of before, as otherwise it's jumping from pasilla to cancer & back to pasilla. Also examining cell types might flow more naturally into single-cell?
- Cibersort, EPIC and ls_fit  - are they only for immune cells/cancer or other studies
- Cibersort, EPIC and ls_fit  - need references 
- some people won't know what LM22 is so needs to be explained or called something more general like immune or blood cell types
- what are PFI.time.2, PFI.2
- there are some warnings that could use some explaining
```
 #> Warning in eval(dots[[i]][[action]], env, env): tidybulk says: highly abundant
#> transcripts were not identified (i.e. identify_abundant()) or filtered (i.e.,
#> keep_abundant), therefore this operation will be performed on unfiltered
#> data. In rare occasions this could be wanted. In standard whole-transcriptome
#> workflows is generally unwanted. - should they be filtered?

#> Warning in as_mapper(.f2)(.x): 
#>                      tidybulk says: In PCA correlation there is < 100 genes that have non NA values is all samples.
#> The correlation calculation would not be reliable,
#> we suggest to partition the dataset for sample clusters. - do we need to do or mention anything about this warning?
```

**Comment by stemangiola** [comment]
Hello Maria,  do you want to have a chat now?

**Comment by mblue9** [comment]
Yep lets do it ..I was just emailing you

**Comment by stemangiola** [comment]
PFI

https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwjX-pPt1ZTsAhW0wjgGHcsDAHcQFjAAegQIBRAC&url=https%3A%2F%2Fwww.ncbi.nlm.nih.gov%2Fpmc%2Farticles%2FPMC6066282%2F&usg=AOvVaw3Ll8KjTEblLYfZ_2PkhE_g

**Comment by mblue9** [comment]
Just noting here for the moment that epic is not mentioned in the `deconvolve_cellularity` help in tidybulk v1.1.8

method | A character string. The method to be used. At the moment Cibersort (default) and llsr (linear least squares regression) are available.

Also epic, llsr, voom references are missing from https://github.com/stemangiola/tidybulk/blob/dev/R/bibliography.R

I think llsr is this one - 
Abbas AR, Wolslegel K, Seshasayee D, Modrusan Z, Clark HF. Deconvolution of blood microarray data identifies cellular activation patterns in systemic lupus erythematosus. PLoS One. 2009;4, e6098.

and think epic is this
https://elifesciences.org/articles/26476

If you want me to add these to tidybulk dev let me know

**Comment by stemangiola** [comment]
Thanks! You are a saviour
