### ISSUE TITLE
survival plot

### ISSUE THREAD

**Issue by mblue9** [stemangiola/rpharma2020_tidytranscriptomics#25]
Just wondering, for this plot what would your conclusion be? 

That it doesn't look like any cell type here has a convincing association with survival?

If so, I know this is just to have an example and using a tiny dataset, so it's fine but for the tidytranscriptomics book would be cool to have a plot that shows this type of analysis can identify a cell type that is associated with survival, but maybe that's not possible.

![survival_plot](https://user-images.githubusercontent.com/5591821/94985177-9270d200-0597-11eb-9f5b-1f48792cdbd0.png)

**Comment by stemangiola** [comment]
This is identified to be 0.08 pvalue significant positively associated. Is not  visually I know.
