### ISSUE TITLE
sentence on identifying cell types from bulk rna-seq vs single-cell

### ISSUE THREAD

**Issue by mblue9** [stemangiola/rpharma2020_tidytranscriptomics#26]
Was thinking that at the moment the workshop reads like you can easily identify cell types from bulk rna-seq so someone might think why bother with single-cell seq then.  Obviously you can do other things with single cell like trajectory analysis but mentioning why cell type identification from bulk isn't perfect/not as good as single-cell cell type identification would be good I think.

Can you think of a sentence or two we could add to explain why? It could go at the end of Part 2?

**Comment by stemangiola** [comment]
Sure. This could be a good transition between cibersort and single cell

**Comment by mblue9** [comment]
Yes was also thinking that too 😄
