### ISSUE TITLE
Refrencing more clearly our introductory material

### ISSUE THREAD

**Issue by stemangiola** [stemangiola/rpharma2020_tidytranscriptomics#30]
I think adding links to our introduction material at the beginning of Part 1 and Part 3 would be beneficial to us (as for reminder) and to the users.

**Comment by mblue9** [comment]
Yep good idea.

**Comment by stemangiola** [comment]
Would you be able to take care of this?

**Comment by mblue9** [comment]
Yep can do I've already added a link to the background just before part 1  and can add a link into part3
