### ISSUE TITLE
TODOs

### ISSUE THREAD

**Issue by mblue9** [stemangiola/rpharma2020_tidytranscriptomics#5]
Making a list of to dos 

Maria
- [x] Use github tagged release versions of tidybulk, tidygate, tidyseurat, tidyHeatmap to make clear what versions we're using
- [x] Exclude the single-cell parts as discussed
- [x] Try putting all workshop sections in 1 file
- [x] Change ensembl_to_symbol to org method as can be used for many species
- [x] Add solutions tab and leave code but remove answers
- [x] Fix warnings
- [x] Make sidebar for solutions to make easy to find by no.
- [x] Add references e.g. deseq2, cibersort, lm22 etc
- [x] Add get_bibliography
- [x] Add small section in Part 2 on action=get and add
- [x] Explain new parts bit more to make clear what the code is doing
- [x] Add instructions/screenshots for how to use the RStudio Cloud project (they need to login & copy project)
- [x] Test install instructions in a fresh RStudio Cloud project (will need to check again if we update any packages)
- [x] Check with R/Pharma when & how we get access to the attendees registration question answers
- [x] Make sure RStudio Cloud project is most recent version (need to git pull changes)
- [x] Docker image (turned off to save time on checks while editing, turn on again by uncommenting in actions file)

Stefano
- [x] Make tagged releases for install instructions for tidybulk (1.1.8), tidygate (0.2.8), tidyseurat (0.1.8), tidyHeatmap (1.1.5)
- [x] Intro to single cell slides/picture? - I have only put one slide on bulk vs single cell in the [slides](https://docs.google.com/presentation/d/1oAx9KZJYUvq2MF4H9hvh11sKH3fxmWrusW80VxP1PhA/edit#slide=id.p), in the [Schedule](https://github.com/stemangiola/rpharma2020_tidytranscriptomics#time-outline) at the moment we have we'll cover "Intro to single cell" before tidyseurat, so should we add a couple more slides on single-cell theory? Should we add a workflow image for tidyseurat like we did for tidybulk?
- [x] Key points for the single cell
- [x] Key points for the part 2
- [x] Only if time (else for future workshops) convert slides to Rmd-
- [x] Make what PFI column are clearer (change headers)
- [x] Create poll questions and answers to Part 2
- [x]  Test i[f workshop rstudio cloud instructions](https://stemangiola.github.io/rpharma2020_tidytranscriptomics/articles/background.html#rstudio-cloud) work & are ok
- [x] Make sure to copy most recent version of RStudio Cloud project before workshop
- [x] Zenodo (create zenodo entry and then update badge/link in README.md

Both
- [x] Create poll questions https://github.com/stemangiola/rpharma2020_tidytranscriptomics/issues/9
- [x] Add poll questions into Rmd

**Comment by mblue9** [comment]
Just noting I tested the updated install_github instructions in Rstudio cloud and get this error ..weird it worked before but could be some changes we've made broke something with knitr

install.packages('remotes')
remotes::install_github(c("stemangiola/tidybulk@v1.1.8", "stemangiola/tidygate@v0.2.8", "stemangiola/tidyseurat@v0.1.8", "stemangiola/tidyHeatmap@v1.1.5"))
remotes::install_github("stemangiola/rpharma2020_tidytranscriptomics", build_vignettes = TRUE)

```
The downloaded source packages are in
	‘/tmp/RtmpRGMgVS/downloaded_packages’
✓  checking for file ‘/tmp/RtmpRGMgVS/remotes11ccc63e14/stemangiola-rpharma2020_tidytranscriptomics-65085ad/DESCRIPTION’ ...
─  preparing ‘rpharma2020tidytranscriptomics’:
✓  checking DESCRIPTION meta-information ...
   Error in loadVignetteBuilder(pkgdir, TRUE) : 
     vignette builder 'knitr' not found
   Execution halted
Error: Failed to install 'rpharma2020tidytranscriptomics' from GitHub:
  System command 'R' failed, exit status: 1, stdout + stderr:
E> * checking for file ‘/tmp/RtmpRGMgVS/remotes11ccc63e14/stemangiola-rpharma2020_tidytranscriptomics-65085ad/DESCRIPTION’ ... OK
E> * preparing ‘rpharma2020tidytranscriptomics’:
E> * checking DESCRIPTION meta-information ... OK
E> Error in loadVignetteBuilder(pkgdir, TRUE) : 
E>   vignette builder 'knitr' not found
E> Execution halted
```

without building vignette it works
remotes::install_github("stemangiola/rpharma2020_tidytranscriptomics")

not a major deal I think, just noting it in case we find a fix and if not I remove the build_vignettes = TRUE from the instructions

**Comment by mblue9** [comment]
Never mind, worked it out, need to update Rmarkdown in rstudio cloud before building the vignette. I'll add this info to the infrastructure notes.

**Comment by stemangiola** [comment]
Thanks Maria! From: mblue9Sent: Wednesday, 30 September 2020 9:06 PMTo: stemangiola/rpharma2020_tidytranscriptomicsCc: SubscribedSubject: Re: [stemangiola/rpharma2020_tidytranscriptomics] TODOs (#5) Never mind, worked it out, need to update Rmarkdown in rstudio cloud before building the vignette. I'll add this info to the infrastructure notes.—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by stemangiola** [comment]
For records new BRCA

```
BRCA =
    readRDS("~/PhD/deconvolution/ARMET/dev/armet_BRCA_input.rds") %>% 
    nanny::nest_subset(data = -patient)  %>% nest(data2 = -alive) %>% 
    mutate(data2 = map(
        data2, 
        ~ .x %>% 
            dplyr::arrange(PFI.time.2) %>%
            dplyr::slice(c(1:5, (n()-5):n()) )
    )) %>% 
    unnest(data2) %>% 
    unnest(data) %>% 
    dplyr::select(patient, transcript, count, contains("PFI")) %>%
    mutate_if(is.character, as.factor) %>%
    mutate(PFI.2 = as.integer(PFI.2)) %>%
    dplyr::rename(time = PFI.time.2, event_happened = PFI.2)
```

**Comment by mblue9** [comment]
FYI the docker build works but I'm going to comment it out again to turn it off while we're still editing as it adds ~30 min to the actions check. We can turn it back on again on Monday or Tuesday morning.

**Comment by mblue9** [comment]
I updated the rstudio cloud instructions, when you get a chance could you test following the instructions using the invitation to the workspace I sent you yesterday, I added it to your todos above 😄

**Comment by stemangiola** [comment]
doing it now

**Comment by stemangiola** [comment]
I was thinking, the section  https://stemangiola.github.io/rpharma2020_tidytranscriptomics/articles/background.html#getting-started states 2 points 

- cloud
- local

as these can be alternative maybe we should not call them 1 2 I got confused myself :)

**Comment by stemangiola** [comment]
Done all working, although I am not sure if the memory profile of my account is the same as the users. All good by the way It worked!

**Comment by mblue9** [comment]
Great thanks for checking! 

I changed to use Cloud and Local as you suggested. Good point!

If you ran it logged in from your wehi email (and not your gmail) then that's the same permissions as the attendees.

They can access the project as long as they accept the invitation to join the RPharma RCloud space. I think we need to invite them into the space, I'll check that tomorrow.  I made your gmail account an Admin for the workspace as if anyone says at the workshop they didn't get the invite then you will need to get their email and invite them to the space if I can't do it if I've started teaching. There's a Members tabs you use to invite them see below

<img width="923" alt="Screen Shot 2020-10-04 at 7 39 02 pm" src="https://user-images.githubusercontent.com/5591821/95011027-80fff680-0679-11eb-94bc-80fba54a37b2.png">

Also forgot to say that version in the cloud is from yesterday and I will need to make sure to add the changes when we're done making changes. I'll add it to my to dos. 

And you will need to make a fresh copy of the most up-to-date project version so you have the right version when you're teaching, I'll add that to your to dos.

**Comment by mblue9** [comment]
By the way I set the cloud project to have the R markdown sidebar turned on by default could you see it? As not 100% sure if it carries over to the copy.

**Comment by stemangiola** [comment]
Are we done with polls? I don't see the issue anymore.

We discussed about changing position of the DE comparison polls as well.

**Comment by mblue9** [comment]
All done :white_check_mark:
