### ISSUE TITLE
rpharma2020_tidytranscriptomics/vignettes/tidytranscriptomics.Rmd

### ISSUE THREAD

**Issue by AMChalkie** [stemangiola/rpharma2020_tidytranscriptomics#8]
Not strictly an issue, more a placeholder for any other comments/additions I might make while I'm poking around.

For the tutorial: 

setup - some libraries used aren't in the setup, and a dynamic install isn't a bad thing:

# tidyverse packages and required libraries
if (!require(BiocManager)){install.packages("BiocManager");library(BiocManager)}
if (!require(tidybulk)){devtools::install_github("stemangiola/tidybulk");library(tidybulk)}
if (!require(Rsubread)){BiocManager::install("Rsubread");library(Rsubread)}

if (!require(tibble)){install.packages("tibble");library(tibble)}
if (!require(dplyr)){install.packages("dplyr");library(dplyr)}
if (!require(tidyr)){install.packages("tidyr");library(tidyr)}
if (!require(readr)){install.packages("readr");library(readr)}
if (!require(stringr)){install.packages("stringr");library(stringr)}
if (!require(ggplot2)){install.packages("ggplot2");library(ggplot2)}
if (!require(ggrepel)){install.packages("ggrepel");library(ggrepel)}
if (!require(plotly)){install.packages("plotly");library(plotly)}

# tidyverse-friendly packages
if (!require(tidyHeatmap)){BiocManager::install("tidyHeatmap");library(tidyHeatmap)}
if (!require(dittoSeq)){BiocManager::install("dittoSeq");library(dittoSeq)}

Also, I have seen in a few places (different tutorials?) that count and counts are not always used consistently. Might be handy to do that and/or have a more firm requirement for one or the other going forward?

**Comment by stemangiola** [comment]
> count and counts are not always used consistently

long term due issue https://github.com/stemangiola/tidybulk/issues/58

____________________________

OK for records looking at it this is a non-issue. Although it looks bad/inconsistent I agree in the context of the tutorials.

Counts comes from the SummarizedExperiment assay name

```
SummarizedExperiment::assays(.data)[1]
List of length 1
names(1): counts
```

Again we don't impose any column name, in case of tibble data source is the user that choose column names, in Case of SE data source is the object that dictate column name. The principle is to stay lean, and not put too much constrain on the system.

As a note, in the future we will be likely (we would like community judgment) basing tidybulk on tidySE, mainly to performance and memory usage. So the whole column name standards will be a bit more consistent.

**Comment by mblue9** [comment]
Thanks for the comments @AMChalkie feel free to poke around and add more.

I'm not sure I understand what you mean about the libraries? are you looking at the workshop content Rmd and the libraries there? For this particular workshop we'll be pre-installing everything in RStudio Cloud or we have instructions in the README if people want to install on their own computers  [here](https://github.com/stemangiola/rpharma2020_tidytranscriptomics#via-github)
```
Alternatively, you could install the workshop using the commands below in R 4.0.

# install.packages('remotes')
remotes::install_github("stemangiola/tidybulk@v1.1.8")
remotes::install_github("stemangiola/rpharma2020_tidytranscriptomics", build_vignettes = TRUE)
library(rpharma2020tidytranscriptomics)
browseVignettes("rpharma2020tidytranscriptomics")
```

**Comment by mblue9** [comment]
altho there's no `stemangiola/tidybulk@v1.1.8` yet it's on @stemangiola todos 😄

**Comment by AMChalkie** [comment]
Another one: https://stemangiola.github.io/bioc_2020_tidytranscriptomics/articles/supplementary.html

significant referenced in MA plot before it is generated.

maplot, minimal

counts_de %>%
    pivot_transcript() %>%
    filter(!lowly_abundant) %>%
    ggplot(aes(x=logCPM, y=-logFC, colour=significant)) +
    geom_point()+
    theme_bw()

This should be added:
  mutate(significant = FDR<0.05 & abs(logFC) >=2) %>%

**Comment by AMChalkie** [comment]
> Thanks for the comments @AMChalkie feel free to poke around and add more.
> 
> I'm not sure I understand what you mean about the libraries? are you looking at the workshop content Rmd and the libraries there? For this particular workshop we'll be pre-installing everything in RStudio Cloud or we have instructions in the README if people want to install on their own computers [here](https://github.com/stemangiola/rpharma2020_tidytranscriptomics#via-github)
> 
> ```
> Alternatively, you could install the workshop using the commands below in R 4.0.
> 
> # install.packages('remotes')
> remotes::install_github("stemangiola/tidybulk@v1.1.8")
> remotes::install_github("stemangiola/rpharma2020_tidytranscriptomics", build_vignettes = TRUE)
> library(rpharma2020tidytranscriptomics)
> browseVignettes("rpharma2020tidytranscriptomics")
> ```

I'm mentioning the library installation for folks that don't go to the workshop and are trying it out from home more than specifically the workshop setting (but yes, people need to know R before jumping into this).

**Comment by stemangiola** [comment]
> 
> 
> altho there's no `stemangiola/tidybulk@v1.1.8` yet it's on @stemangiola todos 😄

Did not understand this one :)

**Comment by mblue9** [comment]
> Another one: https://stemangiola.github.io/bioc_2020_tidytranscriptomics/articles/supplementary.html
> 
> significant referenced in MA plot before it is generated.
> 
> maplot, minimal
> 
> counts_de %>%
> pivot_transcript() %>%
> filter(!lowly_abundant) %>%
> ggplot(aes(x=logCPM, y=-logFC, colour=significant)) +
> geom_point()+
> theme_bw()
> 
> This should be added:
> mutate(significant = FDR<0.05 & abs(logFC) >=2) %>%

It seem you're looking at our old workshop from Bioc2020 https://stemangiola.github.io/bioc_2020_tidytranscriptomics/articles/supplementary.html instead of the current one that's already been updated https://stemangiola.github.io/rpharma2020_tidytranscriptomics/articles/supplementary.html
How did you end up there? as wondering if there's a link we need to update

**Comment by mblue9** [comment]
> Did not understand this one :)

The todos are here https://github.com/stemangiola/rpharma2020_tidytranscriptomics/issues/5 I put 3 for you under your name (I thought your emoji meant you'd read it :smile:) and the rest I'm working through

**Comment by mblue9** [comment]
This workshop is over so closing this, next one is https://github.com/stemangiola/biocasia2020_tidytranscriptomics
