### ISSUE TITLE
workshop polls

### ISSUE THREAD

**Issue by stemangiola** [stemangiola/rpharma2020_tidytranscriptomics#9]

**Comment by stemangiola** [comment]
**Will you code during this workshop?**

Yes 
No

**Do you have experience with Transcriptomic analyses?**

None
Bulk
Bulk and Single-cell

**Do you have experience with tidyverse?**

No
A little
A lot

**what is the method that detects more differentially abundant transcripts?**

DESeq2
edgeR quasi likelihood
edgeR likelihood ratio *
limma-voom

**For the top ranked genes, DESeq2 estimates lower p.values compared to limma-voom. Roughly, around what point of gene rank the significance trend of DESeq2 crosses the one of limma-voom?** 

50th gene
100th gene
1000th gene *
2000th gene

**What is the most abundant cell type overall in BRCA samples**  

Monocytes
Macrophages M1
Macrophages M0 *
Neutrophils

**Comment by mblue9** [comment]
Poll Questions for Part 1 Exercise Solutions

**1) What fraction of variance is explained by PC1?**

0.32
0.47
0.49

0.32 means they didn't run `keep_abundant` before PCA (or they're just guessing)
0.47 is correct
0.49 means they ran `keep_abundant()` instead of `keep_abundant(factor_of_interest = condition)` (or they're just guessing)

**2) How many differentially expressed genes are there for treated vs untreated (FDR < 0.05)?**

685
1064 
1128

685 means they used `~ 0 + condition`  instead of `~ 0 + condition + type`
1064 means they ran `keep_abundant()` instead of `keep_abundant(factor_of_interest = condition)` 
1128 is correct


**3) What is the FBgn id of the 10th most differentially expressed gene (by smallest P value)?**

FBgn0000071 
FBgn0034434
FBgn0051092 

FBgn0000071 is correct
FBgn0034434 means they used `~ 0 + condition`  instead of `~ 0 + condition + type`
FBgn0051092 means they ran `keep_abundant()` instead of `keep_abundant(factor_of_interest = condition)`

**Comment by mblue9** [comment]
At the moment Part 2 Exercises don't fit in a poll but could be good to add a couple of poll questions for those

2.1 How can I compare the amount of differential abundant transcripts for the different methods?
2.2 How can I trace the adjusted p-value rank for methods?

**Comment by stemangiola** [comment]
> At the moment Part 2 Exercises don't fit in a poll but could be good to add a couple of poll questions for those
> 
> 2.1 How can I compare the amount of differential abundant transcripts for the different methods?
> 2.2 How can I trace the adjusted p-value rank for methods?

Didn't I make two exercise about that? Found they are in solutions. Should we use those exercises? They are quite hard though

**Comment by mblue9** [comment]
Yes what I pasted are your current exercise questions :) I copied them from what you added to the Solutions file. But how would they fit in a poll? can you run them into poll questions?

**Comment by stemangiola** [comment]
I was thinking something like 

1) what is the method that detects more differentially abundant transcripts
2) around what value of gene rank the trends cross (or something like that :) )
3) deconvolution question

**Comment by mblue9** [comment]
Ah yes something like that is good!

**Comment by stemangiola** [comment]
This morning I will add the pools to the vignette. I will just add the question to not occupy too much space

**Comment by mblue9** [comment]
Final version of polls

Poll 1

1) Will you code along and/or try out exercises during this workshop?

Yes
No

2) Do you have experience with transcriptomic analyses?

None
Bulk
Single-cell
Bulk and Single-cell

3) Do you have experience with tidyverse?

No
A little
A lot


############################################################################



Poll 2

What fraction of variance is explained by PC3?
35
18
16*




############################################################################



Poll 3

How many differentially expressed transcripts are there for FDR < 0.05 if we did not include cell line in the formula?

4967
2991
1952*

############################################################################



Poll 4

1) What is the Fraction of Variance for PC1?  

0.32
0.47*
0.49


2) How many differentially expressed genes are there for treated vs untreated (FDR < 0.05)? 

685
1064
1128* 


3) What is the FBgn id of the 10th most differentially expressed gene (by smallest P value)?

FBgn0000071*
FBgn0034434
FBgn0051092

############################################################################



Poll 5

Which method detects the most differentially abundant transcripts, p value adjusted for multiple testing <  0.05 (FDR, adj.P.Val, padj)?

DESeq2
edgeR quasi likelihood
edgeR likelihood ratio*
limma-voom

############################################################################




Poll 6

What is the most abundant cell type overall in BRCA samples?

Monocytes
Macrophages M1
Macrophages M0*
Neutrophils


############################################################################

* is correct answer,  code is in solutions.Rmd
